### ISSUE TITLE
panic at shutdown in thread flexi_logger-cleanup

### ISSUE THREAD

**Issue by etam** [golemfactory/yagna#1149]
yagna 0.6.1
```
thread 'flexi_logger-cleanup' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/spawn.rs:131:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
thread 'flexi_logger-cleanup' panicked at 'must be called from the context of Tokio runtime configured with either `basic_scheduler` or `threaded_scheduler`', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/task/spawn.rs:131:10
stack backtrace:
   0:     0x7fe13093dd60 - <unknown>
   1:     0x7fe13080a97c - <unknown>
   2:     0x7fe13093d651 - <unknown>
   3:     0x7fe13093d055 - <unknown>
   4:     0x7fe13093c71b - <unknown>
   5:     0x7fe13095a9c8 - <unknown>
   6:     0x7fe13095a93c - <unknown>
   7:     0x7fe13095a8ed - <unknown>
   8:     0x7fe130808170 - <unknown>
   9:     0x7fe13080f002 - <unknown>
  10:     0x7fe130b9e211 - <unknown>
  11:     0x7fe130939a29 - <unknown>
thread panicked while panicking. aborting.
```

**Comment by tworec** [comment]
not poping up anymore
