### ISSUE TITLE
Debugging ExeUnit problem with result that can't be written

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1437]
```
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/golem/runner.sh', 'args': ('/golem/input/task.pickle', '/golem/output/result.pickle'), 'captu\
re': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 1'; stderr: '+ set -e
+ cd /golem
+ /usr/bin/python3 client.py /golem/input/task.pickle /golem/output/result.pickle
Traceback (most recent call last):
  File "client.py", line 329, in <module>
    asyncio.get_event_loop().run_until_complete(task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "client.py", line 321, in process_pickle
    with open(outpath, mode='wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/golem/output/result.pickle'
```

**Comment by mbenke** [comment]
Sometimes the logs indicate that the payload cannot write to the output file, e.g.

```
yapapi.rest.activity.CommandExecutionError: Command '{'run': {'entry_point': '/golem/runner.sh', 'args': ('/golem/input/task.pickle', '/golem/output/result.pickle'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}' failed on provider; message: 'ExeScript command exited with code 1'; stderr: '+ set -e
+ cd /golem
+ /usr/bin/python3 client.py /golem/input/task.pickle /golem/output/result.pickle
Traceback (most recent call last):
  File "client.py", line 329, in <module>
    asyncio.get_event_loop().run_until_complete(task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "client.py", line 321, in process_pickle
    with open(outpath, mode='wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/golem/output/result.pickle'
```

It happens a bit erratically,  only for some providers, but here also not deterministically: one provider can run the same payload fine, then fail in a few minutes.

**Comment by mfranciszkiewicz** [comment]
@mbenke Could you also share the yapapi log?

**Comment by mbenke** [comment]
@mfranciszkiewicz `golem@88.99.139.166:logs/yagna-1624276417-qQ2_xVKlmSPHE6wCLJaXoQ.log.gz ` has 23 occurrences

**Comment by mfranciszkiewicz** [comment]
This error occurs only on a similarly-named group of providers, which leads me to believe they're controlled by a single person. It appears that `/golem/input` and `/golem/output` directories disappear during computation, but the initial setup is successful - i.e. the directories exist and the initial transfer to `/golem/input` succeeds.

There isn't much more to be read from the log file, which leads me to believe that this person has set up a data directory cleansing job, which ultimately causes this error.

**Comment by nieznanysprawiciel** [comment]
We close this, as it isn't a bug.
We need to observe this, if it occurs again
