### ISSUE TITLE
deploy fails with 416 Range Not Satisfiable

### ISSUE THREAD

**Issue by mbenke** [golemfactory/yagna#1469]
Some deploys fail repeatedly with `with 416 Range Not Satisfiable`. Impact: loss of funds.

```DEBUG:yapapi.events:CommandExecuted(agr_id='1c9b84d309fb2b8868f65625384663759dc3bdc6ce16796cd369d2f9ca79219b', script_id='3568', cmd_idx=0, command={'deploy': {}}, success=F
alse, message='Local service error: Transfer error: HTTP error: client error: 416 Range Not Satisfiable', stdout=None, stderr=None)                                          
DEBUG:yapapi.events:WorkerFinished(agr_id='1c9b84d309fb2b8868f65625384663759dc3bdc6ce16796cd369d2f9ca79219b', exc_info=(<class 'yapapi.rest.activity.CommandExecutionError'>,
 CommandExecutionError({'deploy': {}}, 'Local service error: Transfer error: HTTP error: client error: 416 Range Not Satisfiable', None), <traceback object at 0x7fde2b72e6e0
>))                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                           
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/executor/__init__.py", line 357, in start_worker                                                      
    await self._engine.process_batches(agreement.id, act, batch_generator)                                                                                                   
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 558, in process_batches                                                              
    item = await command_generator.athrow(*sys.exc_info())
  File "server.py", line 1395, in worker
    yield ctx.commit(timeout=subtask_timeout)
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 552, in process_batches                                                             
    results = await get_batch_results()
  File "/root/miniconda3/envs/rdkit/lib/python3.7/site-packages/yapapi/engine.py", line 538, in get_batch_results                                                           
    raise CommandExecutionError(evt.command, evt.message, evt.stderr)
yapapi.rest.activity.CommandExecutionError: Command '{'deploy': {}}' failed on provider; message: 'Local service error: Transfer error: HTTP error: client error: 416 Range $ot Satisfiable'
[2021-06-26T07:34:08.263+0200 WARNING yapapi.summary] Activity failed on provider 'Shreck2-mb'; reason: Command '{'deploy': {}}' failed on provider; message: 'Local service
error: Transfer error: HTTP error: client error: 416 Range Not Satisfiable'
```

**Comment by tworec** [comment]
resolved by #1458
