### ISSUE TITLE
Goth failure: https://github.com/golemfactory/yagna/actions/runs/1460478776

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1679]

**Comment by mfranciszkiewicz** [comment]
Internal goth issue - `zksync` container failed to start

```
2021-11-15 03:18:44+0000 INFO     goth.runner.process            Running local command: docker-compose -f /opt/actions-runner/_work/yagna/yagna/goth_tests/assets/docker/docker-compose.yml up -d
2021-11-15 03:18:44+0000 DEBUG    goth.runner.process            [docker-compose] Creating network "docker_default" with the default driver
2021-11-15 03:18:45+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_proxy-nginx_1 ...
2021-11-15 03:18:45+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_router_1      ...
2021-11-15 03:18:45+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_ethereum_1    ...
2021-11-15 03:18:48+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_ethereum_1    ... done
2021-11-15 03:18:48+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_zksync_1      ...
2021-11-15 03:18:51+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_router_1      ... done
2021-11-15 03:18:52+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_proxy-nginx_1 ... done
2021-11-15 03:18:55+0000 DEBUG    goth.runner.process            [docker-compose] Creating docker_zksync_1      ... done
2021-11-15 03:18:55+0000 DEBUG    goth.runner.process            [docker-compose] 
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [router] Monitor started
2021-11-15 03:18:55+0000 DEBUG    goth.runner.log_monitor        Started LogEventMonitor. name=/tmp/goth-tests/goth_20211115_030416+0000/test_e2e_vm.router
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [proxy-nginx] Monitor started
2021-11-15 03:18:55+0000 DEBUG    goth.runner.log_monitor        Started LogEventMonitor. name=/tmp/goth-tests/goth_20211115_030416+0000/test_e2e_vm.proxy-nginx
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [ethereum] Monitor started
2021-11-15 03:18:55+0000 DEBUG    goth.runner.log_monitor        Started LogEventMonitor. name=/tmp/goth-tests/goth_20211115_030416+0000/test_e2e_vm.ethereum
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [zksync] Monitor started
2021-11-15 03:18:55+0000 DEBUG    goth.runner.log_monitor        Started LogEventMonitor. name=/tmp/goth-tests/goth_20211115_030416+0000/test_e2e_vm.zksync
2021-11-15 03:18:55+0000 INFO     goth.runner.container.compose  Waiting for compose containers to be ready
2021-11-15 03:18:55+0000 DEBUG    goth.runner.container.compose  Waiting for container to be ready. name=ethereum, log_pattern=.*Wallets supplied.
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [ethereum] Assertion 'goth.assertions.monitor.EventMonitor.wait_for_event.wait_for_match' started
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [ethereum] Assertion 'goth.assertions.monitor.EventMonitor.wait_for_event.wait_for_match' finished after event #1 (<LogEvent time=1636946335, level=None, module=None, message=2021-11-15T03:18:55.173787324Z Wallets supplied.,  >)
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [ethereum] Assertion 'goth.assertions.monitor.EventMonitor.wait_for_event.wait_for_match' succeeded; result: <LogEvent time=1636946335, level=None, module=None, message=2021-11-15T03:18:55.173787324Z Wallets supplied.,  >
2021-11-15 03:18:55+0000 DEBUG    goth.runner.log_monitor        Log assertion completed with a match. pattern=.*Wallets supplied., match=2021-11-15T03:18:55.173787324Z Wallets supplied.
2021-11-15 03:18:55+0000 DEBUG    goth.runner.container.compose  Waiting for container to be ready. name=zksync, log_pattern=.*Running on http://.*:3030/.*
2021-11-15 03:18:55+0000 DEBUG    goth.assertions.monitor        [zksync] Assertion 'goth.assertions.monitor.EventMonitor.wait_for_event.wait_for_match' started
2021-11-15 03:19:55+0000 DEBUG    goth.runner.container.compose  Stopping compose network
2021-11-15 03:19:55+0000 DEBUG    goth.runner.container.compose  stopping log monitor. name=router
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [router] Stopping the monitor...
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [router] Monitor stopped
2021-11-15 03:19:55+0000 DEBUG    goth.runner.container.compose  stopping log monitor. name=proxy-nginx
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [proxy-nginx] Stopping the monitor...
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [proxy-nginx] Monitor stopped
2021-11-15 03:19:55+0000 DEBUG    goth.runner.container.compose  stopping log monitor. name=ethereum
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [ethereum] Stopping the monitor...
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [ethereum] Monitor stopped
2021-11-15 03:19:55+0000 DEBUG    goth.runner.container.compose  stopping log monitor. name=zksync
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [zksync] Stopping the monitor...
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [zksync] Assertion 'goth.assertions.monitor.EventMonitor.wait_for_event.wait_for_match' finished after event EndOfEvents
2021-11-15 03:19:55+0000 ERROR    goth.assertions.monitor        [zksync] Assertion 'goth.assertions.monitor.EventMonitor.wait_for_event.wait_for_match' failed; cause: Assertion cancelled
Traceback (most recent call last):
  File "/home/vagrant/.cache/pypoetry/virtualenvs/goth-tests-IwdZBlX0-py3.8/lib/python3.8/site-packages/goth/assertions/assertions.py", line 153, in func_wrapper
    return await self._func(self)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/goth-tests-IwdZBlX0-py3.8/lib/python3.8/site-packages/goth/assertions/monitor.py", line 398, in wait_for_match
    async for e in stream:
  File "/home/vagrant/.cache/pypoetry/virtualenvs/goth-tests-IwdZBlX0-py3.8/lib/python3.8/site-packages/goth/assertions/assertions.py", line 279, in _create_generator
    await self._ready.wait()
  File "/opt/actions-runner/_work/_tool/Python/3.8.0/x64/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

AssertionError: Assertion cancelled
2021-11-15 03:19:55+0000 DEBUG    goth.assertions.monitor        [zksync] Monitor stopped
2021-11-15 03:19:55+0000 INFO     goth.runner.container.compose  Disconnecting container docker_ethereum_1 from network docker_default...
2021-11-15 03:19:55+0000 INFO     goth.runner.container.compose  Disconnecting container docker_proxy-nginx_1 from network docker_default...
2021-11-15 03:19:57+0000 INFO     goth.runner.container.compose  Disconnecting container docker_router_1 from network docker_default...
2021-11-15 03:19:58+0000 INFO     goth.runner.container.compose  Disconnecting container docker_zksync_1 from network docker_default...
2021-11-15 03:19:59+0000 INFO     goth.runner.process            Running local command: docker-compose -f /opt/actions-runner/_work/yagna/yagna/goth_tests/assets/docker/docker-compose.yml down -t 0
```
