### ISSUE TITLE
Flexi-logger panics

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/yagna#1793]
yagna 0.9.1 on macOS Mojave (running as a requestor)

```
2022-01-05T13:20:51.263+0100 ERROR ya_zksync_driver::dao] Failed to fetch unconfirmed transactions : Connection(Error(None))[2022-01-05T13:21:06.262+0100 ERROR ya_zksync_driver::dao] Failed to fetch pending payments for "0x4ce1ca0431e58900012252be1e1297f776caeb02" : Connection(Error(None))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
[2022-01-05T13:21:06.262+0100 ERROR ya_zksync_driver::dao] Failed to fetch pending payments for "0x4ce1ca0431e58900012252be1e1297f776caeb02" : Connection(Error(None))[2022-01-05T13:21:26.259+0100 ERROR ya_zksync_driver::dao] Failed to fetch unconfirmed transactions : Connection(Error(None))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
[2022-01-05T13:21:26.259+0100 ERROR ya_zksync_driver::dao] Failed to fetch unconfirmed transactions : Connection(Error(None))[2022-01-05T13:21:41.263+0100 ERROR ya_zksync_driver::dao] Failed to fetch pending payments for "0x4ce1ca0431e58900012252be1e1297f776caeb02" : Connection(Error(None))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
[2022-01-05T13:21:41.263+0100 ERROR ya_zksync_driver::dao] Failed to fetch pending payments for "0x4ce1ca0431e58900012252be1e1297f776caeb02" : Connection(Error(None))[2022-01-05T13:22:01.259+0100 ERROR ya_zksync_driver::dao] Failed to fetch unconfirmed transactions : Connection(Error(None))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
[2022-01-05T13:22:01.259+0100 ERROR ya_zksync_driver::dao] Failed to fetch unconfirmed transactions : Connection(Error(None))[2022-01-05T13:22:16.262+0100 ERROR ya_zksync_driver::dao] Failed to fetch pending payments for "0x4ce1ca0431e58900012252be1e1297f776caeb02" : Connection(Error(None))
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
^C[2022-01-05T13:22:16.262+0100 ERROR ya_zksync_driver::dao] Failed to fetch pending payments for "0x4ce1ca0431e58900012252be1e1297f776caeb02" : Connection(Error(None))[2022-01-05T13:22:19.978+0100 INFO  actix_server::builder] SIGINT received, exiting
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
[2022-01-05T13:22:19.978+0100 INFO  actix_server::builder] SIGINT received, exiting[2022-01-05T13:22:19.990+0100 INFO  actix_server::builder] SIGINT received, exiting
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
[2022-01-05T13:22:19.990+0100 INFO  actix_server::builder] SIGINT received, exiting[2022-01-05T13:22:19.998+0100 INFO  yagna] yagna service successfully finished!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
Panic in Arbiter thread.
[2022-01-05T13:22:19.998+0100 INFO  yagna] yagna service successfully finished![2022-01-05T13:22:20.028+0100 INFO  ya_service_bus::connection] stopped connection to gsb
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
stack backtrace:
   0:        0x106da73cf - _rustsecp256k1_v0_4_1_default_error_callback_fn
   1:        0x106a13b4b - _main
   2:        0x106da61ba - _rustsecp256k1_v0_4_1_default_error_callback_fn
   3:        0x106da6945 - _rustsecp256k1_v0_4_1_default_error_callback_fn
   4:        0x106da5dfc - _rustsecp256k1_v0_4_1_default_error_callback_fn
   5:        0x106dc735a - _rustsecp256k1_v0_4_1_default_error_callback_fn
   6:        0x106dc72d9 - _rustsecp256k1_v0_4_1_default_error_callback_fn
   7:        0x106dc7295 - _rustsecp256k1_v0_4_1_default_error_callback_fn
   8:        0x107e3f14f - ___rust_probestack
   9:        0x107e3f3f5 - ___rust_probestack
  10:        0x106a4c406 - _main
  11:        0x106a3caf9 - _main
  12:        0x1067a30f5 - __mh_execute_header
  13:        0x1066182a0 - __mh_execute_header
  14:        0x106700368 - __mh_execute_header
  15:        0x106dff9a5 - _rustsecp256k1_v0_4_1_default_error_callback_fn
  16:        0x106658643 - __mh_execute_header
  17:        0x106861dd7 - __mh_execute_header
  18:        0x10660d486 - __mh_execute_header
  19:        0x10686209a - _main
thread panicked while panicking. aborting.
Illegal instruction: 4
thebluebook:~ blue$ 
```

[yagna_rCURRENT.log](https://github.com/golemfactory/yagna/files/7854376/yagna_rCURRENT.log)

**Comment by nieznanysprawiciel** [comment]
@shadeofblue `0.9.1` or `0.9.2`?

**Comment by mfranciszkiewicz** [comment]
The Mutexes were poisoned because the thread panicked with `Too many open files`

![image](https://user-images.githubusercontent.com/3238836/151146933-00fa7601-26d8-460c-81f2-7e0ff10d8787.png)

**Comment by nieznanysprawiciel** [comment]
@shadeofblue Since it is known issue, can we close?

**Comment by nieznanysprawiciel** [comment]
The same error was encountered here: https://github.com/golemfactory/yagna/issues/2385
Maybe flexi-logger update could help?
