### ISSUE TITLE
Analyze benchmarks from `ya-perf`

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2112]

**Comment by wkargul** [comment]
## Files
Results for analysis:
[test_result_hybrid_ya_perf.zip](https://github.com/golemfactory/yagna/files/9242166/test_result_hybrid_ya_perf.zip)
Yagna logs:
[yagna_logs.zip](https://github.com/golemfactory/yagna/files/9242173/yagna_logs.zip)
Yapapi logs:
[yapapi_logs.zip](https://github.com/golemfactory/yagna/files/9242184/yapapi_logs.zip)

## Possible bugs
- This log appears on each run of `ya-perf` checker ➔ ```[2022-08-02T08:36:02.434+0000 WARN  ya_relay_client::session_manager] Forward packet from unknown address: 51.91.209.128:40108. Can't resolve. Sending Disconnected message.```
- Payment issue. Possible reason: task last too long.  ➔
```[2022-08-02T10:35:04.989+0000 DEBUG yapapi.events] PaymentFailed(exception=ApiException(), job=Job(id=1), agreement=Agreement(id=d40f4667eec15b6d432ab68d902fa147a61a76c445f786e4f094c8c421dc7627))
Traceback (most recent call last):
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/yapapi/engine.py", line 415, in _process_invoices
    await invoice.accept(amount=invoice.amount, allocation=allocation)
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/yapapi/rest/common.py", line 78, in wrapper
    return await func(*args, **kwargs)
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/yapapi/rest/payment.py", line 25, in accept
    await self._api.accept_invoice(self.invoice_id, acceptance)
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/ya_payment/api_client.py", line 202, in __call_api
    _request_timeout=_request_timeout,
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/ya_payment/rest.py", line 276, in POST
    body=body,
  File "/home/golem-dev0/checker/hybrid_ya_perf/yapapi-venv/lib/python3.6/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: <CIMultiDictProxy('Content-Length': '88', 'Content-Type': 'application/json', 'Date': 'Tue, 02 Aug 2022 10:35:04 GMT')>
HTTP response body: {"message":"Not enough funds. Allocated: 0.2710979136919999 Needed: 0.3619511033484500"}

[2022-08-02T10:35:04.989+0000 ERROR yapapi.summary] [Job 1] Failed to accept an invoice or a debit note from 'ProviderInfo(id='0x9bcad72b35dba7ba6fb1ac21d4b61a2fc367e39a', name='office_8_80.h', subnet_tag='hybrid')', reason: (400)
```

## Conclusions
### GFTP transfer test ( Requestor ➔ Provider )
- Nodes located in Strasbourg (SBG5, France) are usually faster than others. This seems to be reasonable as location of the checker VM is in Paris (France)
- Upload transfer speed fluctuates usually between 4 to 8 Mbytes/sec (min 0.3 Mbytes/sec, max 10 Mbytes/sec).
- Download transfer speed fluctuates usually between 5 to 9.5 Mbytes/sec (min 0.8 Mbytes/sec, max 11 Mbytes/sec).

### VPN ping test ( Provider ➔ Provider )
- Average ping between nodes at the same location is usually between 35 to 60ms.
Results plot as example: [VPN ping.pdf](https://github.com/golemfactory/yagna/files/9242464/VPN.ping.pdf)
- Average ping between nodes depends on the geographical location of the nodes. Ping usually oscillates between 75 to 150 ms

### VPN transfer test ( Provider ➔ Provider )
- Not much to analyse. Far too weak transfer between providers. Bandwidth oscillates betweeen 0.2 Mbytes/sec to 0.45 MBytes/sec.
Results plot as example: [VPN transfer.pdf](https://github.com/golemfactory/yagna/files/9242630/VPN.transfer.pdf)

**Comment by nieznanysprawiciel** [comment]
This first log, you are mentioning, can happen after Node disconnected, but other Node things he still has connection. I'm not worried about this, because it seems, nothing bad follows.

What is the size of allocation that `yapapi` is making??
I think we should increase it. I think you are right, that tasks are so long, that we don't have enough money.

But this doesn't seem to be a bug related to hybrid, so everything looks clean
