### ISSUE TITLE
golemsp setup fails on Mac (0.11.0, 0.12.0-rc*)

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2308]
```
Initial node setup
Node name  (default=wkargul): 
Ethereum mainnet wallet address (default=0xad1a1cb4ae8e1b12a5e499aaf546514545346f3f): 
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
./as-provider.sh: line 363: 54261 Abort trap: 6           RUST_LOG=error "$_src_core/golemsp" setup 0<&2
```

**Comment by evik42** [comment]
I am running on an Intel Macbook pro with MacOS 11.7.1.
If I run the installer `curl -ksSf https://join.golem.network/as-provider | bash -` it works and installs golem core 0.10.1 and wasi 0.2.2.

If I run the installer and defined YA_INSTALLER_CORE with any of the 0.12 RCs or with the release version 0.11.0 I get the thread local error.
I can reproduce the error by executing `golemsp setup` so it is not a problem with the installer but with golemsp.

**Comment by evik42** [comment]
I debugged it and it happens on the destruction of the main thread. The setup is finished before this error and the next step is also executed (the installer prints out the PATH setup).

<details><summary>actual output</summary>

```
evik@probook ~ % curl -ksSf https://join.golem.network/as-provider | YA_INSTALLER_CORE=pre-rel-v0.12.0-rc9 bash -

By installing & running this software you declare that you have read, understood and hereby accept the disclaimer and
privacy warning found at https://handbook.golem.network/see-also/terms

golem-installer: installing to /Users/evik/.local/bin
 Component                             Version
-----------               --------------------
golem core                          0.12.0-rc9 [done]
wasi runtime                             0.2.2 [done]

                                             ```
                                             ```
                                             ```
                  ```                        ```
       `````````````        `````````        ```        `````````         ``````````````````
     ````      ```        ```       ```      ```      ```       ```       ```     ``     ```
     ``          ``      ```         ```     ```      ``         ```      ``      ``     ```
    ```          ``      ``           ``     ```     ```````````````      ``      ``     ```
     ``          ``      ```         ```     ```      ``                  ``      ``     ```
     ```       ```        ```       ```      ```      ```        `        ``      ``     ```
       `````````            `````````        ```        ``````````        ``      ``     ```
          ```
          ```               version: 0.12.0-rc9
       `````````
     ```       ```          commit: aa6ba83e
     ``          ``
    ```          ``         date: 2022-11-28
     ``          ``
     ````      ```          build: 245
       `````````

Initial node setup
Node name  (default=fat-hot):
Ethereum mainnet wallet address (default=Internal Golem wallet):
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:106:58
stack backtrace:
   0:        0x108216196 - _rust_eh_personality
   1:        0x1080f83bb - _main
   2:        0x1081eabcc - _rust_eh_personality
   3:        0x10821b44c - _rust_eh_personality
   4:        0x10821c3b3 - _rust_eh_personality
   5:        0x10821be9f - _rust_eh_personality
   6:        0x10821be39 - _rust_eh_personality
   7:        0x10821bdf5 - _rust_eh_personality
   8:        0x1084a3065 - ___rust_probestack
   9:        0x10806f686 - _main
  10:        0x1081e9db0 - _rust_eh_personality
  11:     0x7ff80dd1af48 - <unknown>
  12:     0x7ff80dd1aed9 - <unknown>
  13:     0x7ff80df35ae2 - <unknown>
  14:        0x108215d79 - _rust_eh_personality
  15:        0x108215d14 - _rust_eh_personality
  16:        0x107ff229e - __mh_execute_header
  17:        0x10804f09f - __mh_execute_header
  18:        0x107faa956 - __mh_execute_header
  19:        0x10804fbee - _main
  20:     0x7ff80dd0e310 - <unknown>
thread panicked while panicking. aborting.
bash: line 333: 11861 Abort trap: 6           RUST_LOG=error "$_src_core/golemsp" setup 0<&2
golem-installer:
golem-installer: Add /Users/evik/.local/bin to your path
golem-installer: HINT:   echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
golem-installer: Update your current terminal.
golem-installer: HINT:   export PATH="$HOME/.local/bin:$PATH"
```

</details>

**Comment by evik42** [comment]
I managed to pinpoint that `v0.11.0-rc10` works without problems but `v0.11.0-rc11` has this error.
The actual commit that if I revert makes the problem go away in rc11 is https://github.com/golemfactory/yagna/commit/ecb54862aad9da841c34ced67b105327ebfaee12
But it does not introduce any direct change in golem_cli.

**Comment by evik42** [comment]
The stack trace was pointing to the actix_rt annotation on main. Not sure what went wrong but golem_cli is not using actix so I removed the dependency and replaced the runtime with the tokio single threaded one.

**Comment by wkargul** [comment]
So it seems like we need another RC to be tested before the release

**Comment by evik42** [comment]
Relay is investigated as part of: https://github.com/golemfactory/ya-relay/issues/222
