### ISSUE TITLE
Unsubscription of one Demand causes collectEvents for other to return with 404

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#738]
Now with yapapi 0.3.1:
```
Adding /home/etam/code/github/golemfactory/yapapi-0.3.1-community/examples to sys.path.
yapapi version: [33;1m0.3.1[0m
Using subnet: [33;1mcommunity[0m
[2020-10-27 09:55:31,843 INFO yapapi.summary] Demand published on the market
[2020-10-27 09:55:32,728 INFO yapapi.summary] Received proposals from 1 providers so far
[2020-10-27 09:55:32,729 INFO yapapi.summary] Received proposals from 2 providers so far
[2020-10-27 09:55:32,729 INFO yapapi.summary] Received proposals from 3 providers so far
[2020-10-27 09:55:32,729 INFO yapapi.summary] Received proposals from 4 providers so far
[2020-10-27 09:55:32,729 INFO yapapi.summary] Received proposals from 5 providers so far
[2020-10-27 09:55:33,670 INFO yapapi.summary] Received proposals from 6 providers so far
[2020-10-27 09:55:33,775 INFO yapapi.summary] Received proposals from 7 providers so far
[2020-10-27 09:55:33,852 INFO yapapi.summary] Agreement proposed to provider 'snohomish-pot'
[2020-10-27 09:55:33,936 INFO yapapi.summary] Received proposals from 8 providers so far
[2020-10-27 09:55:36,065 INFO yapapi.summary] Agreement confirmed by provider 'snohomish-pot'
[2020-10-27 09:55:37,587 INFO yapapi.summary] Task sent to provider 'snohomish-pot', task data: 0
[2020-10-27 09:55:38,081 INFO yapapi.summary] Agreement proposed to provider 'hesman'
[2020-10-27 09:55:38,504 INFO yapapi.summary] Agreement confirmed by provider 'hesman'
[2020-10-27 09:55:39,984 INFO yapapi.summary] Task sent to provider 'hesman', task data: 10
[2020-10-27 09:55:40,521 INFO yapapi.summary] Agreement proposed to provider 'jamuszyn'
[2020-10-27 09:55:42,361 INFO yapapi.summary] Agreement confirmed by provider 'jamuszyn'
[2020-10-27 09:55:43,411 INFO yapapi.summary] Task sent to provider 'jamuszyn', task data: 20
[2020-10-27 09:55:54,654 INFO yapapi.summary] Task computed by provider 'jamuszyn', task data: 20
[2020-10-27 09:55:54,815 INFO yapapi.summary] Task sent to provider 'jamuszyn', task data: 30
[2020-10-27 09:56:02,412 INFO yapapi.summary] Task computed by provider 'hesman', task data: 10
[2020-10-27 09:56:02,720 INFO yapapi.summary] Task sent to provider 'hesman', task data: 40
[2020-10-27 09:56:05,291 INFO yapapi.summary] Task computed by provider 'jamuszyn', task data: 30
[2020-10-27 09:56:05,454 INFO yapapi.summary] Task sent to provider 'jamuszyn', task data: 50
[2020-10-27 09:56:14,230 INFO yapapi.summary] Task computed by provider 'hesman', task data: 40
[2020-10-27 09:56:15,975 INFO yapapi.summary] Task computed by provider 'jamuszyn', task data: 50
[2020-10-27 10:00:45,531 ERROR yapapi.summary] Computation failed, reason: (404)
Reason: Not Found
HTTP response headers: <CIMultiDictProxy('Content-Length': '152', 'Content-Type': 'application/json', 'Date': 'Tue, 27 Oct 2020 10:00:45 GMT')>
HTTP response body: {"message":"Subscription [8e8964d95bfe4450b3cf3903d0e64245-3e3fdae4027da9d2976da3fbcc40c9209aaf88fab4dfcb151e06bed55efe4e7d] was already unsubscribed."}

[2020-10-27 10:00:45,531 INFO yapapi.rest] activity 6c599ea61c5c4d90905c237981dc5762 CLOSE for [CancelledError] 
Traceback (most recent call last):
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/__init__.py", line 385, in start_worker
    async for batch in command_generator:
  File "../blender.py", line 30, in worker
    async for task in tasks:
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/__init__.py", line 383, in <genexpr>
    (Task.for_handle(handle, work_queue, emit) async for handle in consumer),
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/_smartq.py", line 170, in __anext__
    val = await self._queue.get(self)
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/_smartq.py", line 100, in get
    await self._new_items.wait()
  File "/usr/lib/python3.6/asyncio/locks.py", line 345, in wait
    yield from fut
concurrent.futures._base.CancelledError
[2020-10-27 10:00:45,532 INFO yapapi.rest] activity 7aea96add317467aaabe5f4cbd5ef319 CLOSE for [CancelledError] 
Traceback (most recent call last):
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/__init__.py", line 385, in start_worker
    async for batch in command_generator:
  File "../blender.py", line 30, in worker
    async for task in tasks:
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/__init__.py", line 383, in <genexpr>
    (Task.for_handle(handle, work_queue, emit) async for handle in consumer),
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/_smartq.py", line 170, in __anext__
    val = await self._queue.get(self)
  File "/home/etam/code/github/golemfactory/yapapi-0.3.1-community/yapapi/runner/_smartq.py", line 100, in get
    await self._new_items.wait()
  File "/usr/lib/python3.6/asyncio/locks.py", line 345, in wait
    yield from fut
concurrent.futures._base.CancelledError
[2020-10-27 10:00:45,533 WARNING yapapi.summary] Activity failed on provider 'snohomish-pot', reason: CancelledError()
[2020-10-27 10:00:47,530 INFO yapapi.rest] activity 6c599ea61c5c4d90905c237981dc5762 CLOSE done
[2020-10-27 10:00:47,974 INFO yapapi.rest] activity 7aea96add317467aaabe5f4cbd5ef319 CLOSE done
[36;1mTask computed: Task(id=3, data=20), result: output_20.png[0m
[36;1mTask computed: Task(id=2, data=10), result: output_10.png[0m
[36;1mTask computed: Task(id=4, data=30), result: output_30.png[0m
[36;1mTask computed: Task(id=5, data=40), result: output_40.png[0m
[36;1mTask computed: Task(id=6, data=50), result: output_50.png[0m
```
debug log: [test_debug_2020-10-27_09:55:29.log](https://github.com/golemfactory/yapapi/files/5444417/test_debug_2020-10-27_09.55.29.log)

_Originally posted by @etam in https://github.com/golemfactory/yapapi/issues/76#issuecomment-717129139_

**Comment by tworec** [comment]
here are the logs from @azawlocki who replicated this error easily 

[daemon.log](https://github.com/golemfactory/yagna/files/5448025/daemon.log)
[requestor-1.log](https://github.com/golemfactory/yagna/files/5448028/requestor-1.log)
[requestor-2.log](https://github.com/golemfactory/yagna/files/5448027/requestor-2.log)
